services:
  middleware:
    build: .
    container_name: middleware_service
    environment:
      # DEBUG/INFO gurultu sayilir; ERROR yapilirsa sadece ERROR/CRITICAL islenir.
      - LOG_LEVEL_THRESHOLD=WARNING
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer_service
    environment:
      - MIDDLEWARE_URL=http://middleware:8000/logs
      - PRODUCER_COUNT=100
      - PRODUCER_DELAY=0.1
    depends_on:
      - middleware
